lyft/mapper

- CHANGELOG.md
- Mapper/Mapper.swift
- MapperTests/ConvertibleValueTests.swift
- MapperTests/MappableValueTests.swift
- MapperTests/RawRepresentibleValueTests.swift
Previously `optionalFrom(fields: [String])` was only implemented for "normal" values. This adds implementations for `RawRepresentable`, `Convertible` and `Mappable`
> Implement optionalFrom array of keys for other types

- .gitignore
- .travis.yml
- Makefile
- Resources/coverage.sh
- Tests/ConvertibleValueTests.swift
- Tests/MappableValueTests.swift
- Tests/OptionalValueTests.swift
- Tests/RawRepresentibleValueTests.swift
This parses the profdata file created from running the tests, and
verifies we have 100% coverage. The verification works by ensuring that
no line starts with a "0" which means it was hit 0 times during testing.
I've also added the few tests we were missing for 100% coverage.
> Add test coverage travis build

- CHANGELOG.md
- Sources/Mappable.swift
- Tests/InitializerTests.swift
This adds a new `from` function on `Mappable` in order to create
multiple objects from a `NSArray` of `NSDictionary`s.
> Add Mappable creation from NSArray

- CHANGELOG.md
- Makefile
- Sources/Mappable.swift
- Sources/Mapper.swift
Currently in Swift 2.1, 2.2 and master of apple/swift, `try?` leaks
memory. Until the bug is fixed and released we're replacing all
instances of `try?` with a custom `try_` function that accomplishes the
same thing.
Note, I've left `try?` in the tests since we don't care about the leak there.
- https://bugs.swift.org/browse/SR-972
- https://github.com/apple/swift/pull/1740
> Replace try? with custom try_

- CHANGELOG.md
- Makefile
- Sources/Mappable.swift
- Sources/Mapper.swift
We added this function to work around a memory leak which was fixed in
Swift 2.2.1
> Remove custom `try_` function

- README.md
- Sources/Convertible.swift
- Sources/Mapper.swift
At some point we switched from using `key` to using `field` but never
reflected those changes in the docstrings.
> Update docstrings for correct parameter names

- CHANGELOG.md
- Sources/Mapper.swift
- Tests/Mapper/CustomTransformationTests.swift
- Tests/Mapper/ErrorTests.swift
- Tests/Mapper/TransformTests.swift
When implementing custom errors I decided to make the transformation
function swallow `MissingFieldError`s since we were using `rethrows` and
it would have been a breaking API change. Now we're going to bump for a
breaking API change, and this is more true to what is actually going
wrong in order for the function to throw.
See previous conversation https://github.com/lyft/mapper/pull/48/files#r60854250
> Make transformations throw MissingFieldErrors

- CHANGELOG.md
- Sources/MapperError.swift
- Tests/Mapper/ErrorTests.swift
This was deprecated in the last release. Since we're preparing for a
release with breaking changes, I'm going to go ahead and remove this.
> Remove deprecated MapperError initializer

- .swiftlint.yml
- CHANGELOG.md
- Mapper.xcodeproj/project.pbxproj
- Sources/DefaultConvertible.swift
- Sources/Mapper.swift
- Tests/Mapper/ConvertibleValueTests.swift
- Tests/Mapper/ErrorTests.swift
- Tests/Mapper/NormalValueTests.swift
Previously Mapper worked by conditionally downcasting values to the
expected types. For example:
```
let string: String? = map.optionalFrom("field")
```
Would basically translate to:
```
JSON["field"] as? String?
```
This worked perfectly for many common types, such as `String` and `Int`.
But this became a problem when you used types that could not be
converted like this such as `NSDate`. Previously this line of code would
compile without any additions to Mapper:
```
let date: NSDate? = map.optionalFrom("field")
```
But since this would translate to:
```
JSON["field"] as? NSDate?
```
This would fail 100% of the time. But since it compiled it would leave
callers assuming that it could work. This is no longer the case. Now if
you attempt to cast to a type that doesn't conform to …
> Add compile time safety for all types

- CHANGELOG.md
- Makefile
- Sources/Mapper.swift
- Tests/Mapper/RawRepresentibleValueTests.swift
This enables you to easily take an array in the source data, and get a
strongly typed array of RawRepresentable values. This is heavily
documented to make as obvious as possible the fact that we are
discarding (or replacing) unknown values.
Supersedes https://github.com/lyft/mapper/pull/34
> Add function to create array of RawRepresentables

- CHANGELOG.md
- Tests/Mapper/ConvertibleValueTests.swift
- Tests/Mapper/CustomTransformationTests.swift
- Tests/Mapper/MappableValueTests.swift
- Tests/Mapper/NormalValueTests.swift
- Tests/Mapper/OptionalValueTests.swift
- Tests/Mapper/RawRepresentibleValueTests.swift
- Tests/Mapper/TransformTests.swift
When working on large changes to Mapper, these force trys and force
casts would often end up with annoying test failures. Instead now we
handle the optionals, or the error handling as needed. We also lean a
little bit on the fact that we can remove `throws` from initializers of
`Mappable` and it still works since that isn't part of the function
signature.
> Remove force trys from tests

- CHANGELOG.md
- Mapper.xcodeproj/project.pbxproj
- Sources/Mapper.swift
- Sources/NSDictionary+Safety.swift
- Tests/Mapper/NormalValueTests.swift
Currently `valueForKeyPath:` is a little more generic than we need it to
be, and depending on the scenario this can cause an `NSException` to be
thrown, which cannot be caught from Swift.
Here is a case that will fail:
```swift
let dictionary = ["user": "not dictionary"] as NSDictionary
dictionary.valueForKeyPath("user.phone") // Crashes
```
But really in our use case, we don't care about non-dictionary objects
to be key value coding compliant for the key we're interested in.
Luckily, if the key is nil, it will not crash:
```swift
let dictionary = [:] as NSDictionary
dictionary.valueForKeyPath("user.phone") // Returns nil
```
To fix this, since `valueForKey` also crashes in these cases, we will
instead just treat everything as an `NSDictionary` and fetch the keys
accordingly.
> Replace valueForKeyPath with custom function

- CHANGELOG.md
- Tests/MapperTests/NormalValueTests.swift
As of Swift 3 this test no longer implicitly converts Ints to Doubles.
This is still kind of an issue since that means this feature broke with
Swift 3, but that will be addressed with a future PR.
> Fix TimeInterval test

- CHANGELOG.md
- Mapper.xcodeproj/project.pbxproj
- Tests/MapperTests/JSONSerializationIntegrationTests.swift
Turns out that dictionaries created via `NSJSONSerialization` act
slightly differently than ones created literally through Swift. As far
as we can tell this is caused by the bridging that happens between
Objective-C and Swift. This adds some sanity checks for Double values
specifically since NSNumbers act differently when passed through this
filter.
> Add JSONSerialization integration tests

- CHANGELOG.md
- Mapper.xcodeproj/xcshareddata/xcschemes/Mapper.xcscheme
Since Mapper is a small enough project it doesn't meaningfully impact
compile times to test with optimizations on. The benefit here is that we
won't be surprised when a Swift whole module optimization bug changes
the behavior in a bad way.
> Run tests with release mode

- CHANGELOG.md
- Sources/NSDictionary+Safety.swift
This is the default behavior when extending an Objective-C class, but
this isn't needed for our use.
> Don't expose NSDictionary extension to Objective-C

- CHANGELOG.md
- Mapper.xcodeproj/project.pbxproj
- Mapper.xcodeproj/xcshareddata/xcschemes/Mapper.xcscheme
- Sources/Transform+Dictionary.swift
Swift 4 now has a warning for this, but this is backwards compatible to
Swift 3 as well.
> Remove duplicate Hashable conformation

- CHANGELOG.md
- Sources/NSDictionary+Safety.swift
This isn't deprecated yet, but it is on swiftc master
> Remove characters call from string

- Sources/DefaultConvertible.swift
These are built-in types that applications use often to eliminate variants in
32bit/64bit platforms. A Unix timestamp in milliseconds can't be parsed from
json to an `Int` on 32bit devices, for example.
> Support U?Int(32|64) Conversion Natively

- CHANGELOG.md
- Sources/Mapper.swift
- Tests/MapperTests/CustomTransformationTests.swift
Returns `nil` if key doesn't exist or transformation for found value throws.
> Support Array Of Fields For Custom Transformation

- CHANGELOG.md
- Sources/Mapper.swift
- Tests/MapperTests/ConvertibleValueTests.swift
- Tests/MapperTests/MappableValueTests.swift
- Tests/MapperTests/RawRepresentibleValueTests.swift
This adds support for doing non-optional mapping from a list of fields, similarly to how `map.optionalFrom(["a", "b"])` works.
This allows for usages such this, which was not previously possible:
```
let a = try map.from(["a", "b"])
```
> Support non-optional mapping from list of fields

- CHANGELOG.md
- Mapper.xcodeproj/project.pbxproj
- Sources/DefaultConvertible.swift
- Sources/Float+Convertible.swift
- Tests/MapperTests/ConvertibleValueTests.swift
The behavior of `NSNumber as? Float` in Swift is such that some values
that cannot "safely express the value stored" in NSNumber. This means
only using `as?` to cast to `Float` can fail, where doing `.floatValue`
or `Float.init` would succeed. To work around this oddity, this new
`Convertible` conformance calls `.floatValue` on `NSNumber`, leading to
a float, that is possibly less precise than you'd like.
> Fix Float mapping with downcasting

- Tests/MapperTests/ConvertibleValueTests.swift
This path previously wasn't covered
> Add test for failing Float convertible

- Resources/coverage.sh
Previously if result was not 1, the script would fail with a syntax
error, without exiting with a non-zero exit code. Instead we can compare
to 1 specifically.
> Fix coverage script

- Sources/Mappable.swift
- Sources/Transform+Dictionary.swift
This fixes warnings with the Swift 5 compiler, the contents of these
extensions are explicitly public already, and this will make sure we
don't accidentally add public API that we meant to be internal.
> Remove public from extensions

- CHANGELOG.md
- Sources/NSDictionary+Safety.swift
This removes a now unnecessary cast which also fixes a linker failure in
the Xcode 12 betas
> Fix linker failure on Xcode 12
